---
#Titre de la page à afficher
title: "Curriculum vitae"
output:
  distill::distill_article:
    toc: true
---

<center>

```{r cv, echo = FALSE}

#Functions from jhelvy (https://github.com/jhelvy)
make_icon <- function(icon) {return(htmltools::tag("i", list(class = icon)))}
make_icon_text <- function(icon, text) {return(htmltools::HTML(paste0(make_icon(icon), " ", text)))}
icon_link <- function(icon = NULL, text = NULL, url = NULL) {
  if (!is.null(icon)) {text <- make_icon_text(icon, text)}
  return(htmltools::a(href = url, text, class = "icon-link"))
  }

#Création d'un icone contenant le lien vers le cv 
icon_link(text = "CV", url  = "links/cv.pdf") 
```

</center>

## Research Interests

Multiple stressors & fish

## Publications

Work in progress...

## Skills

Ecology : fish, estuary, rivers, catchments, spawning grounds

Anthopogenic : heatwaves, chemicals

Ecotoxicology : PAF method

Modelisation : time series, linear model

Coding : R (RStudio), SQL (DBeaver), Markdown (Quarto), Git (Github)

Base Microsoft : Word, Excel, Powerpoint

## Research jobs

**INRAE Centre Nouvelle-Aquitaine**

*Cestas-Gazinet (Bordeaux, France) - December 2023 to July 2024*

-   Studying the effects of estuarine heatwaves in fish communities

-   Writing an article

**INRAE Centre Nouvelle-Aquitaine**

*Cestas-Gazinet (Bordeaux, France) - September 2023* *to November 2023*

-   Writing an article : "Assessing the impact of chemical pollution on endangered migratory fish within a catchment using a Potentially Affected Fraction of species (PAF) approach: a case study at main rivers and spawning ground scales"

## Educational background

**Master of "Environmental Sciences" (SPE) in "Environmental Management and Coastal Ecology" (GEEL)**

*La Rochelle University (2021-2023)*

-   Data Analysis, Geographical Information System, Biogeochemical Cycles, Ichtyology, Coastal Sampling, Oceanography, Impacts of Human Activities, *etc.*

-   Protocol for sampling, sorting, selection of biological samples and data analysis in the Baie de l'Aiguillon mudflat

**Master of "Integrated Management of Tropical Coastal Areas" (GIACT)**

*University of Costa Rica (2022-2023)*

-   Courses taught entirely in Spanish

-   Ecological Economics, Oceanography, Politics, Governance, Integrated Tropical Coastal Management, Fisheries Management, *etc.*

-   Protocol for sampling water characteristics in estuaries with different anthropogenic impacts

**License of Organismal and Population Biology (BOP)**

*Angers University (2018-2021)*

-   Genetics, Ecotoxicology, Zoology, Ethology, Physiology, Microbiology, Anatomy, Population Dynamics, *etc.*

**Scientific Baccalaureate in Life and Earth Sciences -- 2018 (sports-study programme)**

*Saint Thomas D'Aquin high school*

-   High-level athlete: organization, autonomy and rigor

## Industry Experience

**Material handler - Temporary (2019)**

*Les Fromageries Perreault*

-   Corporate teamwork

## Volunteer

**4P SCIENSEAS (2022)**

*Photo Project -- Route du Plastique*

-   Bibliographical work to raise public awareness of the problem of plastic pollution
-   Recreational activities to raise public awareness of the problem of plastic pollution

## Sports Awards

**Cyclism (National level)**

*VC Lucéen (2020-2022) - National level*

*Angers Cyclisme (2018-2019) - National level*

*UC Nantes Atlantique (2017) - National level*

**Basket-ball (Regional level)**
